[project]
name = "graphs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "isort==5.13.2",
  "ruff==0.9.1",
  "seaborn==0.13.2"
]
