name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-check:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Check
      run: |
        go vet ./...
        if [ "$(go fmt ./... | wc -l)" -gt 0 ]; then
          echo "your code is not formatted correctly - run 'go fmt ./...' to fix it"
          go fmt ./...
          exit 1
        fi

    # - name: Install dependencies for creating graphs
    #   run: |
    #     cd graphs
    #     curl -LsSf https://astral.sh/uv/install.sh | sh
    #     source $HOME/.local/bin/env
    #     uv venv
    #     . .venv/bin/activate
    #     uv pip install -r requirements.txt
    #
    # - name: Benchmark
    #   run: |
    #     cd graphs
    #     . .venv/bin/activate
    #     cd ../benchmark
    #     go test -bench="." -benchmem . | go run ../v1/internal/benchmark/cmd/main.go | python ../graphs/graphs.py
    #
    # - name: Comment benchmark results
    #   uses: thollander/actions-comment-pull-request@v3
    #   with:
    #     message: |
    #       Hello world ! :wave:
    #   if: github.event_name == 'pull_request'
