name: Release

on:
  push:
    branches: [ "master" ]
    tags:
      - "*"
  pull_request:
    branches: [ "master" ]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install GitPython
          python release/create-tags.py CHANGELOG.md
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install GitPython
          python release/create-releases.py CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
