name: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install GitPython
          python release/create-tags.py
